#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SFA.Apprenticeships.Web.Employer;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Error/InternalServerError.cshtml")]
    public partial class _Views_Error_InternalServerError_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Error_InternalServerError_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Error\InternalServerError.cshtml"
  
    ViewBag.Title = "Service unavailable";
    ViewBag.ErrorCode = 500;
    Layout = "~/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n<p>\r\n    Sorry, there appears to be an error with this page. Please refresh you" +
"r browser or try navigating to <a");

WriteLiteral(" href=\"/Application/Index\"");

WriteLiteral(">my applications</a>. \r\n</p>\r\n");

        }
    }
}
#pragma warning restore 1591
