#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SFA.Apprenticeships.Web.Employer;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Error/NotFound.cshtml")]
    public partial class _Views_Error_NotFound_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Error_NotFound_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Error\NotFound.cshtml"
  
    ViewBag.Title = "Apprenticeship no longer available";
    Layout = "~/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"text\"");

WriteLiteral(">\r\n    <h1");

WriteLiteral(" class=\"heading-xlarge\"");

WriteLiteral(">Apprenticeship no longer available</h1>\r\n</div>\r\n\r\n<div");

WriteLiteral(" class=\"text\"");

WriteLiteral(">\r\n    <p>The apprenticeship you’re applying for is no longer available. This cou" +
"ld be because it’s already been filled or was removed by the employer.</p>\r\n</di" +
"v>\r\n\r\n<p><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Find an apprenticeship</a></p>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
