namespace SFA.Apprenticeships.Application.Interfaces.Messaging
{
    public enum CommunicationTokens
    {
        CandidateFirstName,
        CandidateLastName,
        Username,
        ActivationCode,
        ActivationCodeExpiryDays,
        PasswordResetCode,
        PasswordResetCodeExpiryDays,
        AccountUnlockCode,
        AccountUnlockCodeExpiryDays,
        ApplicationVacancyTitle,
        ApplicationVacancyReference,
        ApplicationId,
        ProviderContact,
        CandidateEmailAddress,
        CandidateMobileNumber,
        ItemCount,
        Item1,
        Item2,
        Item3,
        Item4,
        Item5,
        Item6,
        Item7,
        Item8,
        Item9,
        Item10,
    }
}
