//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFA.Apprenticeships.Infrastructure.LegacyWebServices.GatewayServiceProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Application", Namespace="http://schemas.imservice.org.uk/nas/gatewayservice/1/datatypes")]
    [System.SerializableAttribute()]
    public partial class Application : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CandidateIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VacancyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdditionalQuestionAnswerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VacancyRefField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CandidateId {
            get {
                return this.CandidateIdField;
            }
            set {
                if ((this.CandidateIdField.Equals(value) != true)) {
                    this.CandidateIdField = value;
                    this.RaisePropertyChanged("CandidateId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VacancyId {
            get {
                return this.VacancyIdField;
            }
            set {
                if ((this.VacancyIdField.Equals(value) != true)) {
                    this.VacancyIdField = value;
                    this.RaisePropertyChanged("VacancyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string AdditionalQuestionAnswer {
            get {
                return this.AdditionalQuestionAnswerField;
            }
            set {
                if ((object.ReferenceEquals(this.AdditionalQuestionAnswerField, value) != true)) {
                    this.AdditionalQuestionAnswerField = value;
                    this.RaisePropertyChanged("AdditionalQuestionAnswer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string VacancyRef {
            get {
                return this.VacancyRefField;
            }
            set {
                if ((object.ReferenceEquals(this.VacancyRefField, value) != true)) {
                    this.VacancyRefField = value;
                    this.RaisePropertyChanged("VacancyRef");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ValidationErrors", Namespace="http://schemas.imservices.org.uk/nas/gatewayservice/1/datatypes", ItemName="ValidationError")]
    [System.SerializableAttribute()]
    public class ValidationErrors : System.Collections.Generic.List<SFA.Apprenticeships.Infrastructure.LegacyWebServices.GatewayServiceProxy.ValidationError> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidationError", Namespace="http://schemas.imservices.org.uk/nas/gatewayservice/1/datatypes")]
    [System.SerializableAttribute()]
    public partial class ValidationError : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KeyData {
            get {
                return this.KeyDataField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyDataField, value) != true)) {
                    this.KeyDataField = value;
                    this.RaisePropertyChanged("KeyData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Candidate", Namespace="http://schemas.imservices.org.uk/nas/gatewayservice/1/datatypes")]
    [System.SerializableAttribute()]
    public partial class Candidate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TownCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LandlineTelephoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileTelephoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress {
            get {
                return this.EmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddressField, value) != true)) {
                    this.EmailAddressField = value;
                    this.RaisePropertyChanged("EmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiddleName {
            get {
                return this.MiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddleNameField, value) != true)) {
                    this.MiddleNameField = value;
                    this.RaisePropertyChanged("MiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime DateOfBirth {
            get {
                return this.DateOfBirthField;
            }
            set {
                if ((this.DateOfBirthField.Equals(value) != true)) {
                    this.DateOfBirthField = value;
                    this.RaisePropertyChanged("DateOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string AddressLine1 {
            get {
                return this.AddressLine1Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine1Field, value) != true)) {
                    this.AddressLine1Field = value;
                    this.RaisePropertyChanged("AddressLine1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string AddressLine2 {
            get {
                return this.AddressLine2Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine2Field, value) != true)) {
                    this.AddressLine2Field = value;
                    this.RaisePropertyChanged("AddressLine2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string AddressLine3 {
            get {
                return this.AddressLine3Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine3Field, value) != true)) {
                    this.AddressLine3Field = value;
                    this.RaisePropertyChanged("AddressLine3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string AddressLine4 {
            get {
                return this.AddressLine4Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine4Field, value) != true)) {
                    this.AddressLine4Field = value;
                    this.RaisePropertyChanged("AddressLine4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string TownCity {
            get {
                return this.TownCityField;
            }
            set {
                if ((object.ReferenceEquals(this.TownCityField, value) != true)) {
                    this.TownCityField = value;
                    this.RaisePropertyChanged("TownCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string County {
            get {
                return this.CountyField;
            }
            set {
                if ((object.ReferenceEquals(this.CountyField, value) != true)) {
                    this.CountyField = value;
                    this.RaisePropertyChanged("County");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string Postcode {
            get {
                return this.PostcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostcodeField, value) != true)) {
                    this.PostcodeField = value;
                    this.RaisePropertyChanged("Postcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public string LandlineTelephone {
            get {
                return this.LandlineTelephoneField;
            }
            set {
                if ((object.ReferenceEquals(this.LandlineTelephoneField, value) != true)) {
                    this.LandlineTelephoneField = value;
                    this.RaisePropertyChanged("LandlineTelephone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public string MobileTelephone {
            get {
                return this.MobileTelephoneField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileTelephoneField, value) != true)) {
                    this.MobileTelephoneField = value;
                    this.RaisePropertyChanged("MobileTelephone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.imservices.org.uk/nas/gatewayservice/1", ConfigurationName="GatewayServiceProxy.GatewayServiceContract")]
    public interface GatewayServiceContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.imservices.org.uk/nas/gatewayservice/1/CreateApplication", ReplyAction="http://schemas.imservices.org.uk/nas/gatewayservice/1/GatewayServiceContract/Crea" +
            "teApplicationResponse")]
        SFA.Apprenticeships.Infrastructure.LegacyWebServices.GatewayServiceProxy.CreateApplicationResponse CreateApplication(SFA.Apprenticeships.Infrastructure.LegacyWebServices.GatewayServiceProxy.CreateApplicationRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.imservices.org.uk/nas/gatewayservice/1/CreateApplication", ReplyAction="http://schemas.imservices.org.uk/nas/gatewayservice/1/GatewayServiceContract/Crea" +
            "teApplicationResponse")]
        System.Threading.Tasks.Task<SFA.Apprenticeships.Infrastructure.LegacyWebServices.GatewayServiceProxy.CreateApplicationResponse> CreateApplicationAsync(SFA.Apprenticeships.Infrastructure.LegacyWebServices.GatewayServiceProxy.CreateApplicationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.imservices.org.uk/nas/gatewayservice/1/GatewayServiceContract/Crea" +
            "teCandidate", ReplyAction="http://schemas.imservices.org.uk/nas/gatewayservice/1/GatewayServiceContract/Crea" +
            "teCandidateResponse")]
        SFA.Apprenticeships.Infrastructure.LegacyWebServices.GatewayServiceProxy.CreateCandidateResponse CreateCandidate(SFA.Apprenticeships.Infrastructure.LegacyWebServices.GatewayServiceProxy.CreateCandidateRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.imservices.org.uk/nas/gatewayservice/1/GatewayServiceContract/Crea" +
            "teCandidate", ReplyAction="http://schemas.imservices.org.uk/nas/gatewayservice/1/GatewayServiceContract/Crea" +
            "teCandidateResponse")]
        System.Threading.Tasks.Task<SFA.Apprenticeships.Infrastructure.LegacyWebServices.GatewayServiceProxy.CreateCandidateResponse> CreateCandidateAsync(SFA.Apprenticeships.Infrastructure.LegacyWebServices.GatewayServiceProxy.CreateCandidateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateApplicationRequest", WrapperNamespace="http://schemas.imservices.org.uk/nas/gatewayservice/1", IsWrapped=true)]
    public partial class CreateApplicationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.imservices.org.uk/nas/gatewayservice/1", Order=0)]
        public SFA.Apprenticeships.Infrastructure.LegacyWebServices.GatewayServiceProxy.Application Application;
        
        public CreateApplicationRequest() {
        }
        
        public CreateApplicationRequest(SFA.Apprenticeships.Infrastructure.LegacyWebServices.GatewayServiceProxy.Application Application) {
            this.Application = Application;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateApplicationResponse", WrapperNamespace="http://schemas.imservices.org.uk/nas/gatewayservice/1", IsWrapped=true)]
    public partial class CreateApplicationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.imservices.org.uk/nas/gatewayservice/1", Order=0)]
        public int ApplicationId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.imservices.org.uk/nas/gatewayservice/1", Order=1)]
        public SFA.Apprenticeships.Infrastructure.LegacyWebServices.GatewayServiceProxy.ValidationErrors ValidationErrors;
        
        public CreateApplicationResponse() {
        }
        
        public CreateApplicationResponse(int ApplicationId, SFA.Apprenticeships.Infrastructure.LegacyWebServices.GatewayServiceProxy.ValidationErrors ValidationErrors) {
            this.ApplicationId = ApplicationId;
            this.ValidationErrors = ValidationErrors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateCandidateRequest", WrapperNamespace="http://schemas.imservices.org.uk/nas/gatewayservice/1", IsWrapped=true)]
    public partial class CreateCandidateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.imservices.org.uk/nas/gatewayservice/1", Order=0)]
        public SFA.Apprenticeships.Infrastructure.LegacyWebServices.GatewayServiceProxy.Candidate Candidate;
        
        public CreateCandidateRequest() {
        }
        
        public CreateCandidateRequest(SFA.Apprenticeships.Infrastructure.LegacyWebServices.GatewayServiceProxy.Candidate Candidate) {
            this.Candidate = Candidate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateCandidateResponse", WrapperNamespace="http://schemas.imservices.org.uk/nas/gatewayservice/1", IsWrapped=true)]
    public partial class CreateCandidateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.imservices.org.uk/nas/gatewayservice/1", Order=0)]
        public int CandidateId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.imservices.org.uk/nas/gatewayservice/1", Order=1)]
        public SFA.Apprenticeships.Infrastructure.LegacyWebServices.GatewayServiceProxy.ValidationErrors ValidationErrors;
        
        public CreateCandidateResponse() {
        }
        
        public CreateCandidateResponse(int CandidateId, SFA.Apprenticeships.Infrastructure.LegacyWebServices.GatewayServiceProxy.ValidationErrors ValidationErrors) {
            this.CandidateId = CandidateId;
            this.ValidationErrors = ValidationErrors;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GatewayServiceContractChannel : SFA.Apprenticeships.Infrastructure.LegacyWebServices.GatewayServiceProxy.GatewayServiceContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GatewayServiceContractClient : System.ServiceModel.ClientBase<SFA.Apprenticeships.Infrastructure.LegacyWebServices.GatewayServiceProxy.GatewayServiceContract>, SFA.Apprenticeships.Infrastructure.LegacyWebServices.GatewayServiceProxy.GatewayServiceContract {
        
        public GatewayServiceContractClient() {
        }
        
        public GatewayServiceContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GatewayServiceContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GatewayServiceContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GatewayServiceContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SFA.Apprenticeships.Infrastructure.LegacyWebServices.GatewayServiceProxy.CreateApplicationResponse SFA.Apprenticeships.Infrastructure.LegacyWebServices.GatewayServiceProxy.GatewayServiceContract.CreateApplication(SFA.Apprenticeships.Infrastructure.LegacyWebServices.GatewayServiceProxy.CreateApplicationRequest request) {
            return base.Channel.CreateApplication(request);
        }
        
        public int CreateApplication(SFA.Apprenticeships.Infrastructure.LegacyWebServices.GatewayServiceProxy.Application Application, out SFA.Apprenticeships.Infrastructure.LegacyWebServices.GatewayServiceProxy.ValidationErrors ValidationErrors) {
            SFA.Apprenticeships.Infrastructure.LegacyWebServices.GatewayServiceProxy.CreateApplicationRequest inValue = new SFA.Apprenticeships.Infrastructure.LegacyWebServices.GatewayServiceProxy.CreateApplicationRequest();
            inValue.Application = Application;
            SFA.Apprenticeships.Infrastructure.LegacyWebServices.GatewayServiceProxy.CreateApplicationResponse retVal = ((SFA.Apprenticeships.Infrastructure.LegacyWebServices.GatewayServiceProxy.GatewayServiceContract)(this)).CreateApplication(inValue);
            ValidationErrors = retVal.ValidationErrors;
            return retVal.ApplicationId;
        }
        
        public System.Threading.Tasks.Task<SFA.Apprenticeships.Infrastructure.LegacyWebServices.GatewayServiceProxy.CreateApplicationResponse> CreateApplicationAsync(SFA.Apprenticeships.Infrastructure.LegacyWebServices.GatewayServiceProxy.CreateApplicationRequest request) {
            return base.Channel.CreateApplicationAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SFA.Apprenticeships.Infrastructure.LegacyWebServices.GatewayServiceProxy.CreateCandidateResponse SFA.Apprenticeships.Infrastructure.LegacyWebServices.GatewayServiceProxy.GatewayServiceContract.CreateCandidate(SFA.Apprenticeships.Infrastructure.LegacyWebServices.GatewayServiceProxy.CreateCandidateRequest request) {
            return base.Channel.CreateCandidate(request);
        }
        
        public int CreateCandidate(SFA.Apprenticeships.Infrastructure.LegacyWebServices.GatewayServiceProxy.Candidate Candidate, out SFA.Apprenticeships.Infrastructure.LegacyWebServices.GatewayServiceProxy.ValidationErrors ValidationErrors) {
            SFA.Apprenticeships.Infrastructure.LegacyWebServices.GatewayServiceProxy.CreateCandidateRequest inValue = new SFA.Apprenticeships.Infrastructure.LegacyWebServices.GatewayServiceProxy.CreateCandidateRequest();
            inValue.Candidate = Candidate;
            SFA.Apprenticeships.Infrastructure.LegacyWebServices.GatewayServiceProxy.CreateCandidateResponse retVal = ((SFA.Apprenticeships.Infrastructure.LegacyWebServices.GatewayServiceProxy.GatewayServiceContract)(this)).CreateCandidate(inValue);
            ValidationErrors = retVal.ValidationErrors;
            return retVal.CandidateId;
        }
        
        public System.Threading.Tasks.Task<SFA.Apprenticeships.Infrastructure.LegacyWebServices.GatewayServiceProxy.CreateCandidateResponse> CreateCandidateAsync(SFA.Apprenticeships.Infrastructure.LegacyWebServices.GatewayServiceProxy.CreateCandidateRequest request) {
            return base.Channel.CreateCandidateAsync(request);
        }
    }
}
