#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFA.Apprenticeships.Web.Candidate.Views.ApprenticeshipSearch
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SFA.Apprenticeships.Web.Candidate;
    using SFA.Apprenticeships.Web.Candidate.Constants;
    using SFA.Apprenticeships.Web.Candidate.Constants.ViewModels;
    
    #line 1 "..\..\Views\ApprenticeshipSearch\_searchUpdate.cshtml"
    using SFA.Apprenticeships.Web.Candidate.Extensions;
    
    #line default
    #line hidden
    using SFA.Apprenticeships.Web.Candidate.Helpers;
    using SFA.Apprenticeships.Web.Candidate.ViewModels;
    using SFA.Apprenticeships.Web.Candidate.ViewModels.Candidate;
    using SFA.Apprenticeships.Web.Candidate.ViewModels.Locations;
    using SFA.Apprenticeships.Web.Candidate.ViewModels.Login;
    using SFA.Apprenticeships.Web.Candidate.ViewModels.Register;
    using SFA.Apprenticeships.Web.Candidate.ViewModels.VacancySearch;
    using SFA.Apprenticeships.Web.Common.Constants;
    using SFA.Apprenticeships.Web.Common.Framework;
    using SFA.Apprenticeships.Web.Common.Models.Common;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/ApprenticeshipSearch/_searchUpdate.cshtml")]
    public partial class searchUpdate : System.Web.Mvc.WebViewPage<ApprenticeshipSearchViewModel>
    {
        public searchUpdate()
        {
        }
        public override void Execute()
        {
WriteLiteral("<section");

WriteLiteral(" class=\"grid grid-1-3\"");

WriteLiteral(">\r\n    <div>\r\n        <fieldset");

WriteLiteral(" class=\"search-filter\"");

WriteLiteral(">\r\n\r\n            <legend");

WriteLiteral(" class=\"heading-medium mob-collpanel-trigger\"");

WriteLiteral(" id=\"editSearchToggle\"");

WriteLiteral(">Edit search</legend>\r\n            <div");

WriteLiteral(" class=\"mob-collpanel toggle-content--mob\"");

WriteLiteral(" id=\"editSearchPanel\"");

WriteLiteral(">\r\n                <nav");

WriteLiteral(" class=\"tabbed-nav\"");

WriteLiteral(">\r\n");

            
            #line 11 "..\..\Views\ApprenticeshipSearch\_searchUpdate.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 11 "..\..\Views\ApprenticeshipSearch\_searchUpdate.cshtml"
                      
                        var searchTabControlUrl = Url.ApprenticeshipSearchViewModelAction("results", new ApprenticeshipSearchViewModel(Model) {SearchMode = ApprenticeshipSearchMode.Keyword});
                        var browseTabControlUrl = Url.ApprenticeshipSearchViewModelAction("results", new ApprenticeshipSearchViewModel(Model) {SearchMode = ApprenticeshipSearchMode.Category});
                        var searchTabControlClass = Model.SearchMode == ApprenticeshipSearchMode.Keyword ? " active" : "";
                        var browseTabControlClass = Model.SearchMode == ApprenticeshipSearchMode.Category ? " active" : "";

                        var categoriesElementControlClass = Model.SearchMode == ApprenticeshipSearchMode.Category && Model.Categories != null && Model.Categories.Any() ? " active" : "";
                        var categoriesTabClass = Model.Categories != null && Model.Categories.Any() ? " tab2" : "";
                        var elementControlClass = Model.SearchMode == ApprenticeshipSearchMode.Keyword ? searchTabControlClass : categoriesElementControlClass;                        
                    
            
            #line default
            #line hidden
WriteLiteral("\r\n                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1610), Tuple.Create("\"", 1637)
            
            #line 21 "..\..\Views\ApprenticeshipSearch\_searchUpdate.cshtml"
, Tuple.Create(Tuple.Create("", 1617), Tuple.Create<System.Object, System.Int32>(searchTabControlUrl
            
            #line default
            #line hidden
, 1617), false)
);

WriteLiteral(" id=\"search-tab-control\"");

WriteAttribute("class", Tuple.Create(" class=\"", 1662), Tuple.Create("\"", 1703)
, Tuple.Create(Tuple.Create("", 1670), Tuple.Create("tabbed-tab", 1670), true)
            
            #line 21 "..\..\Views\ApprenticeshipSearch\_searchUpdate.cshtml"
            , Tuple.Create(Tuple.Create(" ", 1680), Tuple.Create<System.Object, System.Int32>(searchTabControlClass
            
            #line default
            #line hidden
, 1681), false)
);

WriteLiteral(" tab=\"#tab1\"");

WriteLiteral(">Search</a>\r\n                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1751), Tuple.Create("\"", 1778)
            
            #line 22 "..\..\Views\ApprenticeshipSearch\_searchUpdate.cshtml"
, Tuple.Create(Tuple.Create("", 1758), Tuple.Create<System.Object, System.Int32>(browseTabControlUrl
            
            #line default
            #line hidden
, 1758), false)
);

WriteLiteral(" id=\"browse-tab-control\"");

WriteAttribute("class", Tuple.Create(" class=\"", 1803), Tuple.Create("\"", 1844)
, Tuple.Create(Tuple.Create("", 1811), Tuple.Create("tabbed-tab", 1811), true)
            
            #line 22 "..\..\Views\ApprenticeshipSearch\_searchUpdate.cshtml"
            , Tuple.Create(Tuple.Create(" ", 1821), Tuple.Create<System.Object, System.Int32>(browseTabControlClass
            
            #line default
            #line hidden
, 1822), false)
);

WriteLiteral(" tab=\"#tab2\"");

WriteLiteral(">Browse</a>\r\n                </nav>\r\n                <div");

WriteLiteral(" class=\"tabbed-content active\"");

WriteLiteral(">\r\n\r\n");

WriteLiteral("                    ");

            
            #line 26 "..\..\Views\ApprenticeshipSearch\_searchUpdate.cshtml"
               Write(Html.Partial("_categoriesAndSubCategories", Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 27 "..\..\Views\ApprenticeshipSearch\_searchUpdate.cshtml"
               Write(Html.FormTextFor(m => m.Keywords, hintText: "", containerHtmlAttributes: new { @class = "tabbed-element tab1" + searchTabControlClass }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 28 "..\..\Views\ApprenticeshipSearch\_searchUpdate.cshtml"
               Write(Html.FormTextFor(m => m.Location, hintText: "", containerHtmlAttributes: new { @class = "tabbed-element tab1" + categoriesTabClass + elementControlClass}));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 30 "..\..\Views\ApprenticeshipSearch\_searchUpdate.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 30 "..\..\Views\ApprenticeshipSearch\_searchUpdate.cshtml"
                     if (Model.LocationSearches != null && Model.LocationSearches.Length > 0)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <details open");

WriteAttribute("class", Tuple.Create(" class=\"", 2515), Tuple.Create("\"", 2619)
, Tuple.Create(Tuple.Create("", 2523), Tuple.Create("open", 2523), true)
, Tuple.Create(Tuple.Create(" ", 2527), Tuple.Create("form-group", 2528), true)
, Tuple.Create(Tuple.Create(" ", 2538), Tuple.Create("form-group-compound", 2539), true)
, Tuple.Create(Tuple.Create(" ", 2558), Tuple.Create("tabbed-element", 2559), true)
, Tuple.Create(Tuple.Create(" ", 2573), Tuple.Create("tab1", 2574), true)
            
            #line 32 "..\..\Views\ApprenticeshipSearch\_searchUpdate.cshtml"
                    , Tuple.Create(Tuple.Create(" ", 2578), Tuple.Create<System.Object, System.Int32>(categoriesTabClass
            
            #line default
            #line hidden
, 2579), false)
            
            #line 32 "..\..\Views\ApprenticeshipSearch\_searchUpdate.cshtml"
                                        , Tuple.Create(Tuple.Create(" ", 2598), Tuple.Create<System.Object, System.Int32>(elementControlClass
            
            #line default
            #line hidden
, 2599), false)
);

WriteLiteral(" id=\"locationSuggestions\"");

WriteLiteral(">\r\n                            <summary");

WriteLiteral(" tabindex=\"0\"");

WriteLiteral(" aria-describedby=\"locSuggestionsAria\"");

WriteLiteral(">Did you mean:</summary>\r\n                            <p");

WriteLiteral(" class=\"visuallyhidden\"");

WriteLiteral(" aria-live=\"polite\"");

WriteLiteral(" id=\"locSuggestionsAria\"");

WriteLiteral("></p>\r\n                            <div");

WriteLiteral(" class=\"detail-content panel-indent\"");

WriteLiteral(">\r\n                                <ul");

WriteLiteral(" id=\"location-suggestions\"");

WriteLiteral(" class=\"list-text list-max-11\"");

WriteLiteral(">\r\n");

            
            #line 37 "..\..\Views\ApprenticeshipSearch\_searchUpdate.cshtml"
                                    
            
            #line default
            #line hidden
            
            #line 37 "..\..\Views\ApprenticeshipSearch\_searchUpdate.cshtml"
                                     foreach (var locationSearch in Model.LocationSearches)
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 3207), Tuple.Create("\"", 3252)
            
            #line 39 "..\..\Views\ApprenticeshipSearch\_searchUpdate.cshtml"
, Tuple.Create(Tuple.Create("", 3214), Tuple.Create<System.Object, System.Int32>(Url.Action("results", locationSearch)
            
            #line default
            #line hidden
, 3214), false)
);

WriteLiteral(">");

            
            #line 39 "..\..\Views\ApprenticeshipSearch\_searchUpdate.cshtml"
                                                                                        Write(locationSearch.Location);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 40 "..\..\Views\ApprenticeshipSearch\_searchUpdate.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                </ul>\r\n                            </div>\r\n      " +
"                  </details>\r\n");

            
            #line 44 "..\..\Views\ApprenticeshipSearch\_searchUpdate.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteAttribute("class", Tuple.Create(" class=\"", 3486), Tuple.Create("\"", 3565)
, Tuple.Create(Tuple.Create("", 3494), Tuple.Create("form-group", 3494), true)
, Tuple.Create(Tuple.Create(" ", 3504), Tuple.Create("tabbed-element", 3505), true)
, Tuple.Create(Tuple.Create(" ", 3519), Tuple.Create("tab1", 3520), true)
            
            #line 45 "..\..\Views\ApprenticeshipSearch\_searchUpdate.cshtml"
, Tuple.Create(Tuple.Create(" ", 3524), Tuple.Create<System.Object, System.Int32>(categoriesTabClass
            
            #line default
            #line hidden
, 3525), false)
            
            #line 45 "..\..\Views\ApprenticeshipSearch\_searchUpdate.cshtml"
  , Tuple.Create(Tuple.Create(" ", 3544), Tuple.Create<System.Object, System.Int32>(elementControlClass
            
            #line default
            #line hidden
, 3545), false)
);

WriteLiteral(">\r\n                        <label");

WriteLiteral(" for=\" loc-within\"");

WriteLiteral(" class=\"form-label\"");

WriteLiteral(">\r\n                        Within</label>\r\n");

WriteLiteral("                        ");

            
            #line 48 "..\..\Views\ApprenticeshipSearch\_searchUpdate.cshtml"
                   Write(Html.DropDownListFor(m => m.WithinDistance, Model.Distances, new { @id = "loc-within", @name = "WithinDistance" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                    <div");

WriteAttribute("class", Tuple.Create(" class=\"", 3872), Tuple.Create("\"", 3951)
, Tuple.Create(Tuple.Create("", 3880), Tuple.Create("form-group", 3880), true)
, Tuple.Create(Tuple.Create(" ", 3890), Tuple.Create("tabbed-element", 3891), true)
, Tuple.Create(Tuple.Create(" ", 3905), Tuple.Create("tab1", 3906), true)
            
            #line 50 "..\..\Views\ApprenticeshipSearch\_searchUpdate.cshtml"
, Tuple.Create(Tuple.Create(" ", 3910), Tuple.Create<System.Object, System.Int32>(categoriesTabClass
            
            #line default
            #line hidden
, 3911), false)
            
            #line 50 "..\..\Views\ApprenticeshipSearch\_searchUpdate.cshtml"
  , Tuple.Create(Tuple.Create(" ", 3930), Tuple.Create<System.Object, System.Int32>(elementControlClass
            
            #line default
            #line hidden
, 3931), false)
);

WriteLiteral(">\r\n                        <label");

WriteLiteral(" for=\"apprenticeship-level\"");

WriteLiteral(" class=\"form-label\"");

WriteLiteral(">Apprenticeship level</label>\r\n");

WriteLiteral("                        ");

            
            #line 52 "..\..\Views\ApprenticeshipSearch\_searchUpdate.cshtml"
                   Write(Html.DropDownListFor(m => m.ApprenticeshipLevel, Model.ApprenticeshipLevels, new { @id = "apprenticeship-level", @name = "ApprenticeshipLevel" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                    <div");

WriteAttribute("class", Tuple.Create(" class=\"", 4286), Tuple.Create("\"", 4365)
, Tuple.Create(Tuple.Create("", 4294), Tuple.Create("form-group", 4294), true)
, Tuple.Create(Tuple.Create(" ", 4304), Tuple.Create("tabbed-element", 4305), true)
, Tuple.Create(Tuple.Create(" ", 4319), Tuple.Create("tab1", 4320), true)
            
            #line 54 "..\..\Views\ApprenticeshipSearch\_searchUpdate.cshtml"
, Tuple.Create(Tuple.Create(" ", 4324), Tuple.Create<System.Object, System.Int32>(categoriesTabClass
            
            #line default
            #line hidden
, 4325), false)
            
            #line 54 "..\..\Views\ApprenticeshipSearch\_searchUpdate.cshtml"
  , Tuple.Create(Tuple.Create(" ", 4344), Tuple.Create<System.Object, System.Int32>(elementControlClass
            
            #line default
            #line hidden
, 4345), false)
);

WriteLiteral(">\r\n                        <button");

WriteLiteral(" class=\"button no-btm-margin\"");

WriteLiteral(" id=\"search-button\"");

WriteLiteral(" name=\"SearchAction\"");

WriteLiteral(" value=\"Search\"");

WriteLiteral(">Update results</button>\r\n                    </div>\r\n                    <div");

WriteAttribute("class", Tuple.Create(" class=\"", 4561), Tuple.Create("\"", 4664)
, Tuple.Create(Tuple.Create("", 4569), Tuple.Create("form-group", 4569), true)
, Tuple.Create(Tuple.Create(" ", 4579), Tuple.Create("map-container", 4580), true)
, Tuple.Create(Tuple.Create(" ", 4593), Tuple.Create("hide-nojs", 4594), true)
, Tuple.Create(Tuple.Create(" ", 4603), Tuple.Create("tabbed-element", 4604), true)
, Tuple.Create(Tuple.Create(" ", 4618), Tuple.Create("tab1", 4619), true)
            
            #line 57 "..\..\Views\ApprenticeshipSearch\_searchUpdate.cshtml"
      , Tuple.Create(Tuple.Create(" ", 4623), Tuple.Create<System.Object, System.Int32>(categoriesTabClass
            
            #line default
            #line hidden
, 4624), false)
            
            #line 57 "..\..\Views\ApprenticeshipSearch\_searchUpdate.cshtml"
                          , Tuple.Create(Tuple.Create(" ", 4643), Tuple.Create<System.Object, System.Int32>(elementControlClass
            
            #line default
            #line hidden
, 4644), false)
);

WriteLiteral(">\r\n                        <div");

WriteLiteral(" id=\"map-canvas\"");

WriteLiteral(" style=\"width: 100%; height: 250px\"");

WriteLiteral("></div>\r\n                    </div>\r\n\r\n");

WriteLiteral("                    ");

            
            #line 61 "..\..\Views\ApprenticeshipSearch\_searchUpdate.cshtml"
               Write(Html.HiddenFor(m => m.Latitude));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 62 "..\..\Views\ApprenticeshipSearch\_searchUpdate.cshtml"
               Write(Html.HiddenFor(m => m.Longitude));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 63 "..\..\Views\ApprenticeshipSearch\_searchUpdate.cshtml"
               Write(Html.Hidden("Hash", Model.LatLonLocHash()));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 64 "..\..\Views\ApprenticeshipSearch\_searchUpdate.cshtml"
               Write(Html.HiddenFor(m => m.SearchMode));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    ");

WriteLiteral("\r\n                    <input");

WriteLiteral(" id=\"LocationType\"");

WriteLiteral(" name=\"LocationType\"");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("value", Tuple.Create(" value=\"", 5284), Tuple.Create("\"", 5311)
            
            #line 66 "..\..\Views\ApprenticeshipSearch\_searchUpdate.cshtml"
      , Tuple.Create(Tuple.Create("", 5292), Tuple.Create<System.Object, System.Int32>(Model.LocationType
            
            #line default
            #line hidden
, 5292), false)
);

WriteLiteral(" />\r\n\r\n                </div>\r\n            </div>\r\n        </fieldset>\r\n    </div" +
">\r\n</section>");

        }
    }
}
#pragma warning restore 1591
