namespace SFA.Apprenticeships.Application.Interfaces.Communications
{
    public enum CommunicationTokens
    {
        CandidateFirstName,
        CandidateLastName,
        Username,
        ActivationCode,
        ActivationCodeExpiryDays,
        PasswordResetCode,
        PasswordResetCodeExpiryDays,
        AccountUnlockCode,
        AccountUnlockCodeExpiryDays,
        MobileVerificationCode,
        ApplicationVacancyTitle,
        ApplicationVacancyReference,
        ApplicationVacancyEmployerName,
        ApplicationId,
        ProviderContact,
        RecipientEmailAddress,
        CandidateMobileNumber,
        ExpiringDraftsCount,
        ExpiringDrafts,
        UserFullName,
        UserEnquiry,
        UserEnquiryDetails,
        UserEmailAddress
    }
}
