#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFA.Apprenticeships.Web.Candidate.Views.TraineeshipSearch
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SFA.Apprenticeships.Web.Candidate;
    using SFA.Apprenticeships.Web.Candidate.Constants;
    using SFA.Apprenticeships.Web.Candidate.Constants.ViewModels;
    using SFA.Apprenticeships.Web.Candidate.Helpers;
    using SFA.Apprenticeships.Web.Candidate.ViewModels;
    using SFA.Apprenticeships.Web.Candidate.ViewModels.Candidate;
    using SFA.Apprenticeships.Web.Candidate.ViewModels.Locations;
    using SFA.Apprenticeships.Web.Candidate.ViewModels.Login;
    using SFA.Apprenticeships.Web.Candidate.ViewModels.Register;
    using SFA.Apprenticeships.Web.Candidate.ViewModels.VacancySearch;
    using SFA.Apprenticeships.Web.Common.Constants;
    using SFA.Apprenticeships.Web.Common.Framework;
    using SFA.Apprenticeships.Web.Common.Models.Common;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/TraineeshipSearch/Overview.cshtml")]
    public partial class Overview : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Overview()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\TraineeshipSearch\Overview.cshtml"
  
    ViewBag.Title = "Traineeship overview - Find a traineeship";
    Layout = "~/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<section");

WriteLiteral(" class=\"text\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"text\"");

WriteLiteral(">\r\n        <h1");

WriteLiteral(" class=\"heading-xlarge\"");

WriteLiteral(">Are you eligible for a traineeship?</h1>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"text\"");

WriteLiteral(" id=\"tshipAbout\"");

WriteLiteral(@">
        <section>
            <p>
                A traineeship is designed to prepare someone for an apprenticeship
                or get them ready for work. They can take up to 6 months.
            </p>
            <p>
                You’ll get:
            </p>
            <ul>
                <li>help with English and maths (if you need it)</li>
                <li>a work experience placement</li>
            </ul>
            <p>You can apply for a traineeship if you’re:</p>
        </section>
        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n            <h2");

WriteLiteral(" class=\"heading-medium heading-with-check\"");

WriteLiteral(">\r\n                <i");

WriteLiteral(" class=\"fa fa-check-square-o font-large\"");

WriteLiteral("></i>\r\n                eligible to work in England\r\n            </h2>\r\n        </" +
"div>\r\n        <div");

WriteLiteral(" class=\"form-group inline\"");

WriteLiteral(">\r\n            <h2");

WriteLiteral(" class=\"heading-medium heading-with-check\"");

WriteLiteral(">\r\n                <i");

WriteLiteral(" class=\"fa fa-check-square-o font-large\"");

WriteLiteral("></i>\r\n                unemployed or work less than 16 hours a week\r\n            " +
"</h2>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n            <h2");

WriteLiteral(" class=\"heading-medium heading-with-check\"");

WriteLiteral(">\r\n                <i");

WriteLiteral(" class=\"fa fa-check-square-o font-large\"");

WriteLiteral("></i>\r\n                aged 16 to 24 and qualified below Level 3\r\n            </h" +
"2>\r\n            <details>\r\n                <summary>More about qualifications</s" +
"ummary>\r\n                <div");

WriteLiteral(" class=\"panel-indent detail-content\"");

WriteLiteral(@">
                    <p>Level 2 qualifications are equivalent to 5 GCSEs (Grades A*-C).</p>
                    <p>Level 3 qualifications are equivalent to 2 or more A-levels.</p>
                </div>
            </details>
        </div>
        <div");

WriteLiteral(" class=\"panel-indent\"");

WriteLiteral(@">
            <p>
                Traineeships are unpaid, but employers can sometimes pay expenses for
                things like travel and meals.
            </p>
            <p>
                If you're unsure if a traineeship is right for you, contact the <a");

WriteLiteral(" rel=\"external\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(" href=\"https://nationalcareersservice.direct.gov.uk\"");

WriteLiteral(">National Careers Service</a> for\r\n                advice.\r\n            </p>\r\n   " +
"     </div>\r\n        <div");

WriteLiteral(" class=\"get-started form-group\"");

WriteLiteral(">\r\n            <a");

WriteLiteral(" id=\"prompt-traineeship-search-link\"");

WriteAttribute("href", Tuple.Create(" href=", 2526), Tuple.Create("", 2584)
            
            #line 61 "..\..\Views\TraineeshipSearch\Overview.cshtml"
, Tuple.Create(Tuple.Create("", 2532), Tuple.Create<System.Object, System.Int32>(Url.RouteUrl(CandidateRouteNames.TraineeshipSearch)
            
            #line default
            #line hidden
, 2532), false)
);

WriteLiteral(" class=\"button\"");

WriteLiteral(">Find a traineeship</a>\r\n        </div>\r\n        <p>\r\n            Alternatively, " +
"if you think you\'d be eligible for an apprenticeship,\r\n            use the ");

            
            #line 65 "..\..\Views\TraineeshipSearch\Overview.cshtml"
               Write(Html.RouteLink("Find an apprenticeship", CandidateRouteNames.ApprenticeshipSearch, null));

            
            #line default
            #line hidden
WriteLiteral(" service\r\n            instead.\r\n        </p>\r\n    </div>\r\n </section>\r\n");

        }
    }
}
#pragma warning restore 1591
